### ISSUE TITLE
Enhance hompage

### ISSUE THREAD

**Issue by buihoanghai** [maihuynhtruc/learnReactJS#112]
"**User story**
 user thay dc sp noi bat, sp moi ngay tren homepage
**Requirement**
 
**Acceptance Criteria**"
![Image of Yaktocat](https://scontent.fkul14-1.fna.fbcdn.net/v/t1.0-9/37204450_1443605639073924_670696964752408576_n.jpg?_nc_cat=0&oh=e6a27a72c3358d3b5f8cc52429b5bbab&oe=5BE32EEE)

**Comment by maihuynhtruc** [comment]
**Latest products**:
Show 8 products (2 per type)

**Latest articles**:
Show 10 products per type

**Popular products**:
Show 8 products (2 per type) 

**Popular articles**:
Show 10 products per type
