### ISSUE TITLE
check search keywords dau gac

### ISSUE THREAD

**Issue by maihuynhtruc** [maihuynhtruc/learnReactJS#64]
sprint5 trien khai search keyword dau gac de check xem 1 sprint có change dc luot tuong tac ko

**Comment by buihoanghai** [comment]
Sau khi thử nghiệm 8 ngày thì thấy nhờ mọi nguời search Kết quả cũng không rõ ràng. 
Giờ sẽ thử nghiệm = cách không cần search nhưng vẫn check thứ tự trong 1 vòng 7 ngày tiếp.
