### ISSUE TITLE
Create new back links 

### ISSUE THREAD

**Issue by buihoanghai** [maihuynhtruc/learnReactJS#65]

**Comment by buihoanghai** [comment]
Play around how to create back link.
Bookmark links of the most biggest forums in VN

**Comment by maihuynhtruc** [comment]
dang ky và posted
 https://www.lamchame.com/forum/threads/dieu-tri-nam-da-lam-cach-nao-tot-nhat.2288675/
https://www.webtretho.com/forum/f3268/toi-da-tri-triet-de-nam-bang-cach-nay-2684134/#post36626412
